### ISSUE TITLE
Add support for 2BPP viewing mode

### ISSUE THREAD

**Issue by Kaisaan** [romhack/PsxVram-DotNet#5]
Some games such as Shin Megami Tensei: Devil Children Black Book & Red Book have graphics that seem to be in 2BPP format such as its text font graphics. It would be useful to have support for 2BPP since I'm not really able to properly convert exported 4BPP or 8BPP files to 2BPP.

**Comment by romhack** [comment]
Hi, Kaisaan.
This is tool for viewing PS1 VRAM contents. GPU has [only 4 texture mapping color mode](https://www.psdevwiki.com/ps1/GPU)
Each game can have resources stored in any color mode, including 2BPP. But the game code will have to convert the graphics into one of these 4 modes and copy it to the GPU so that it can render the texture.
Therefore, the available four modes are sufficient if you want to view the graphics of the video memory contents. 
If you want to view the graphics in format of the game's resource files, you can open the file in a tile editor such as TileMolester and choose the appropriate mode.
